"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from petstore import utils
from petstore.types import BaseModel


class APIErrorNotFoundData(BaseModel):
    status: int

    error: str

    code: str


class APIErrorNotFound(Exception):
    r"""Not Found error"""

    data: APIErrorNotFoundData

    def __init__(self, data: APIErrorNotFoundData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, APIErrorNotFoundData)
