"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from petstore.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class APIResponseTypedDict(TypedDict):
    code: NotRequired[int]
    type: NotRequired[str]
    message: NotRequired[str]


class APIResponse(BaseModel):
    code: Optional[int] = None

    type: Optional[str] = None

    message: Optional[str] = None
