"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from petstore.types import BaseModel
from petstore.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class GetOrderByIDRequestTypedDict(TypedDict):
    order_id: int
    r"""ID of order that needs to be fetched"""


class GetOrderByIDRequest(BaseModel):
    order_id: Annotated[
        int,
        pydantic.Field(alias="orderId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of order that needs to be fetched"""
