"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from petstore.types import BaseModel
from petstore.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class GetPetByIDRequestTypedDict(TypedDict):
    pet_id: int
    r"""ID of pet to return"""


class GetPetByIDRequest(BaseModel):
    pet_id: Annotated[
        int,
        pydantic.Field(alias="petId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of pet to return"""
