"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from petstore.types import BaseModel
from petstore.utils import FieldMetadata, QueryParamMetadata
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LoginUserRequestTypedDict(TypedDict):
    username: NotRequired[str]
    r"""The user name for login"""
    password: NotRequired[str]
    r"""The password for login in clear text"""


class LoginUserRequest(BaseModel):
    username: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The user name for login"""

    password: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The password for login in clear text"""


class LoginUserResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: str


class LoginUserResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: str
