"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from petstore.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OrderStatus(str, Enum):
    r"""Order Status"""

    PLACED = "placed"
    APPROVED = "approved"
    DELIVERED = "delivered"


class OrderTypedDict(TypedDict):
    id: NotRequired[int]
    pet_id: NotRequired[int]
    quantity: NotRequired[int]
    ship_date: NotRequired[datetime]
    status: NotRequired[OrderStatus]
    r"""Order Status"""
    complete: NotRequired[bool]


class Order(BaseModel):
    id: Optional[int] = None

    pet_id: Annotated[Optional[int], pydantic.Field(alias="petId")] = None

    quantity: Optional[int] = None

    ship_date: Annotated[Optional[datetime], pydantic.Field(alias="shipDate")] = None

    status: Optional[OrderStatus] = None
    r"""Order Status"""

    complete: Optional[bool] = None
